# Generated by Django 5.0.1 on 2024-03-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='User',
        ),
    ]
