# Generated by Django 5.0.1 on 2024-03-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_signup_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
